# docker-compose.yml
version: '3.8'

services:
  flask_app:
    build: 
      context: . # Dockerfile is located in the same directory as docker-compose.yml
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/scoringapp.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx config directory
    depends_on:
      - flask_app
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"]

networks:
  app_network:
    driver: bridge

