# docker-compose.yml
version: '3.8'

services:
  flask_app:
    build: 
      context: . # Dockerfile is located in the same directory as docker-compose.yml
    container_name: flask-app
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx:
    image: nginx:latest # this image is specific to Azure. Perhaps use nginx:latest for other platforms
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/scoringapp.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx config directory ${WEBAPP_STORAGE_HOME} is specific to Azure
    depends_on:
      - flask_app
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"]

networks:
  app_network:
    driver: bridge

