# docker-compose.yml
version: '3.8'

services:
  flask_app1:
    image: flaskapp:latest
    ports:
      - "8000:8000"
    networks:
      - app_network

  flask_app2:
    image: flaskapp:latest
    ports:
      - "8001:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/scoringapp.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx config directory
    depends_on:
      - flask_app1
      - flask_app2
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"]

networks:
  app_network:
    driver: bridge

